# Generated by Django 4.2.7 on 2023-12-01 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='developers', verbose_name='Фото разработчика')),
                ('title', models.CharField(max_length=31, verbose_name='Разработчик')),
                ('description', models.CharField(blank=True, max_length=127, null=True, verbose_name='Описание разработчика')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=17, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='tokens', verbose_name='Фото проекта')),
                ('title', models.CharField(max_length=31, verbose_name='Проект')),
                ('ticker', models.CharField(max_length=7, verbose_name='Тикер')),
                ('description', models.CharField(blank=True, max_length=127, null=True, verbose_name='Описание проекта')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.developer', verbose_name='Тег разработчика проекта')),
                ('tags', models.ManyToManyField(to='main.tag', verbose_name='Тег проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Другое', 'Другое'), ('Перевод', 'Перевод'), ('Покупка', 'Покупка'), ('Продажа', 'Продажа')], max_length=10, verbose_name='Тип транзакции')),
                ('qnt', models.FloatField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.token', verbose_name='Токен транзакции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор транзакции')),
            ],
        ),
        migrations.CreateModel(
            name='SavedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.ManyToManyField(to='main.token', verbose_name='Проекты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор избранного по проектам')),
            ],
        ),
        migrations.CreateModel(
            name='SavedDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developers', models.ManyToManyField(to='main.developer', verbose_name='Разработчики')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор избранного по разработчикам')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='tags',
            field=models.ManyToManyField(to='main.tag', verbose_name='Тег разработчика'),
        ),
    ]
