# Generated by Django 4.2.7 on 2023-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(choices=[('Продажа', 'Продажа'), ('Покупка', 'Покупка'), ('Другое', 'Другое'), ('Перевод', 'Перевод')], max_length=10, verbose_name='Тип транзакции'),
        ),
    ]
