# Generated by Django 4.2.7 on 2023-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(choices=[('Другое', 'Другое'), ('Перевод', 'Перевод'), ('Продажа', 'Продажа'), ('Покупка', 'Покупка')], max_length=10, verbose_name='Тип транзакции'),
        ),
    ]
